"""Docker packaging: turn a model file into a runnable container image.

The build context is assembled in a temporary directory (unless ``--keep-context``
is used), so repeated runs never inherit stale files from a previous build.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from formats import require_format

DEFAULT_PYTHON_VERSION = "3.11"
SUPPORT_FILES = ("infer.py", "model_loader.py", "formats.py")
SAMPLE_IMAGE = "sample.jpg"

DOCKERFILE = """\
# Generated by ai-model-packager - do not edit by hand.
FROM {base_image}

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \\
 && pip install --no-cache-dir -r requirements.txt

COPY {support_files} ./
COPY {model_filename} ./
{sample_copy}
# Run as an unprivileged user; the model and scripts stay read-only to it.
RUN useradd --create-home --uid 10001 appuser && chown -R appuser:appuser /app
USER appuser

ENTRYPOINT ["python", "infer.py", "--model", "{model_filename}"]
CMD [{default_args}]
"""

DOCKERIGNORE = """\
__pycache__/
*.pyc
.git/
"""


class DockerUnavailableError(RuntimeError):
    """Raised when the Docker CLI or daemon cannot be reached."""


class PackagingError(RuntimeError):
    """Raised when a packaging step fails."""


# --------------------------------------------------------------------------- #
# Docker availability
# --------------------------------------------------------------------------- #
def check_docker_available(quiet: bool = False) -> bool:
    """Report whether the Docker daemon is running and responsive.

    Args:
        quiet: Suppress progress output.

    Returns:
        True if ``docker version`` succeeds, False otherwise.
    """

    def say(message: str) -> None:
        if not quiet:
            print(message)

    try:
        say("Checking Docker daemon availability...")
        result = subprocess.run(
            ["docker", "version", "--format", "json"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except subprocess.TimeoutExpired:
        say("TIMEOUT: Docker daemon check timed out")
        say("INFO: try restarting Docker Desktop or the docker service")
        return False
    except FileNotFoundError:
        say("ERROR: 'docker' command not found - Docker may not be installed")
        return False
    except OSError as exc:
        say(f"ERROR: Docker check failed: {exc}")
        return False

    if result.returncode == 0:
        say("SUCCESS: Docker daemon is running and responsive")
        return True

    say("ERROR: Docker daemon is not responding")
    if result.stderr:
        say(f"Details: {result.stderr.strip()}")
    return False


# --------------------------------------------------------------------------- #
# Validation helpers
# --------------------------------------------------------------------------- #
def validate_image_name(image_name: str) -> str:
    """Validate a Docker image reference and return it unchanged.

    Raises:
        ValueError: If the reference is empty or uses illegal characters.
    """
    if not image_name or not isinstance(image_name, str):
        raise ValueError("Image name must be a non-empty string")

    name, _, tag = image_name.partition(":")
    if not name:
        raise ValueError(f"Invalid image name: {image_name!r}")
    if any(ch.isspace() for ch in image_name):
        raise ValueError("Image name must not contain whitespace")
    if name != name.lower():
        raise ValueError("Docker image names must be lowercase")
    if "" == tag and ":" in image_name:
        raise ValueError(f"Image tag is empty in {image_name!r}")
    return image_name


def _base_image(python_version: str) -> str:
    """Base image reference for the requested Python version."""
    return f"python:{python_version}-slim"


# --------------------------------------------------------------------------- #
# Build context assembly
# --------------------------------------------------------------------------- #
def create_sample_image(sample_path) -> bool:
    """Create a 224x224 placeholder JPEG if one does not already exist.

    Returns:
        True if a usable sample image exists after the call.
    """
    sample_path = Path(sample_path)
    if sample_path.exists():
        return True

    try:
        from PIL import Image
    except ImportError:
        print("INFO: Pillow not installed - packaging without a sample image")
        return False

    try:
        Image.new("RGB", (224, 224), "steelblue").save(sample_path)
        return True
    except OSError as exc:
        print(f"WARNING: failed to create sample image: {exc}")
        return False


def build_context(model_path, context_dir, python_version=DEFAULT_PYTHON_VERSION) -> Path:
    """Assemble a Docker build context for ``model_path`` in ``context_dir``.

    Writes the Dockerfile, a format-specific ``requirements.txt``, the support
    scripts, the model file and (when Pillow is available) a sample image.

    Returns:
        The context directory as a :class:`Path`.

    Raises:
        FileNotFoundError: If the model or a required support script is missing.
        ValueError: If the model format is unsupported.
    """
    model_file = Path(model_path)
    if not model_file.exists():
        raise FileNotFoundError(f"Model file not found: {model_path}")

    fmt = require_format(model_file)
    context = Path(context_dir)
    context.mkdir(parents=True, exist_ok=True)

    shutil.copy(model_file, context / model_file.name)

    requirements = "\n".join(fmt.pip_requirements) + "\n"
    (context / "requirements.txt").write_text(requirements, encoding="utf-8")

    project_root = Path(__file__).resolve().parent
    for script in SUPPORT_FILES:
        source = project_root / script
        if not source.exists():
            raise FileNotFoundError(f"Required support script not found: {script}")
        shutil.copy(source, context / script)

    has_sample = create_sample_image(context / SAMPLE_IMAGE)
    default_args = f'"--test-input", "{SAMPLE_IMAGE}"' if has_sample else ""

    (context / "Dockerfile").write_text(
        DOCKERFILE.format(
            base_image=_base_image(python_version),
            support_files=" ".join(SUPPORT_FILES),
            model_filename=model_file.name,
            sample_copy=f"COPY {SAMPLE_IMAGE} ./\n" if has_sample else "",
            default_args=default_args,
        ),
        encoding="utf-8",
    )
    (context / ".dockerignore").write_text(DOCKERIGNORE, encoding="utf-8")

    return context


# --------------------------------------------------------------------------- #
# Build
# --------------------------------------------------------------------------- #
def _docker_build_command(image_name, context, platform=None, no_cache=False):
    """Assemble the ``docker build`` argument list."""
    cmd = ["docker", "build", "-t", image_name]
    if platform:
        cmd += ["--platform", platform]
    if no_cache:
        cmd.append("--no-cache")
    cmd.append(str(context))
    return cmd


def _verify_docker_image(image_name: str) -> bool:
    """Check that the freshly built image is listed by ``docker images``."""
    try:
        result = subprocess.run(
            ["docker", "images", image_name, "--format", "{{.Repository}}:{{.Tag}}"],
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (subprocess.TimeoutExpired, OSError) as exc:
        print(f"WARNING: image verification skipped: {exc}")
        return True

    if result.returncode == 0 and image_name in result.stdout:
        print(f"VERIFIED: image {image_name} exists and is ready to use")
        return True

    print("WARNING: build reported success but the image could not be verified")
    return True


def package_model(
    model_path,
    image_name,
    python_version: str = DEFAULT_PYTHON_VERSION,
    platform: Optional[str] = None,
    no_cache: bool = False,
    keep_context: bool = False,
    context_dir: Optional[str] = None,
) -> bool:
    """Build a Docker image containing the model and its inference environment.

    Args:
        model_path: Path to the model file to package.
        image_name: Docker image reference, e.g. ``my_model:1.0``.
        python_version: Python version for the ``python:<v>-slim`` base image.
        platform: Optional target platform, e.g. ``linux/amd64``.
        no_cache: Pass ``--no-cache`` to ``docker build``.
        keep_context: Keep the generated build context on disk after the build.
        context_dir: Directory for the build context. Defaults to
            ``build_context`` when ``keep_context`` is set, otherwise a
            temporary directory that is removed afterwards.

    Returns:
        True if the image was built successfully.

    Raises:
        DockerUnavailableError: If the Docker daemon cannot be reached.
        FileNotFoundError: If the model or a support script is missing.
        ValueError: If the image name or model format is invalid.
    """
    validate_image_name(image_name)
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model file not found: {model_path}")
    require_format(model_path)

    if not check_docker_available():
        raise DockerUnavailableError("Docker is not available")

    if keep_context or context_dir:
        target = Path(context_dir or "build_context")
        if target.exists():
            shutil.rmtree(target)
        cleanup = None
    else:
        tmp = tempfile.mkdtemp(prefix="ai_model_packager_")
        target = Path(tmp)
        cleanup = tmp

    try:
        print(f"Creating Docker build context in: {target}")
        context = build_context(model_path, target, python_version=python_version)

        print(f"Building Docker image: {image_name}")
        print("Dependencies are downloaded on first build - this can take several minutes")

        cmd = _docker_build_command(image_name, context, platform, no_cache)
        print(f"Running: {' '.join(cmd)}")
        print("=" * 60)
        result = subprocess.run(cmd, check=False)
        print("=" * 60)

        if result.returncode != 0:
            raise PackagingError(
                f"docker build failed with exit code {result.returncode}"
            )

        print(f"SUCCESS: built Docker image: {image_name}")
        _verify_docker_image(image_name)
        print("\nNext steps:")
        print(f"   - Run inference:  docker run --rm {image_name}")
        print(f"   - Custom input:   docker run --rm -v $PWD:/data {image_name} "
              "--test-input /data/your_image.jpg")
        return True
    finally:
        if cleanup:
            shutil.rmtree(cleanup, ignore_errors=True)
